In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("online_retail.csv")
print(df.head())

   index InvoiceNo StockCode                          Description  Quantity  \
0      0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1      1    536365     71053                  WHITE METAL LANTERN         6
2      2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3      3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4      4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

      InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/2010 8:26       2.55     17850.0  United Kingdom
1  12/1/2010 8:26       3.39     17850.0  United Kingdom
2  12/1/2010 8:26       2.75     17850.0  United Kingdom
3  12/1/2010 8:26       3.39     17850.0  United Kingdom
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [4]:
df.shape

(541909, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        541909 non-null  int64
 1   InvoiceNo    541909 non-null  object
 2   StockCode    541909 non-null  object
 3   Description  540455 non-null  object
 4   Quantity     541909 non-null  int64
 5   InvoiceDate  541909 non-null  object
 6   UnitPrice    541909 non-null  float64
 7   CustomerID   406829 non-null  float64
 8   Country      541909 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 37.2+ MB

In [6]:
df.describe()

              index       Quantity      UnitPrice     CustomerID
count  541909.00000  541909.000000  541909.000000  406829.000000
mean   270954.00000       9.552250       4.611114   15287.690570
std    156435.79785     218.081158      96.759853    1713.600303
min         0.00000  -80995.000000  -11062.060000   12346.000000
25%    135477.00000       1.000000       1.250000   13953.000000
50%    270954.00000       3.000000       2.080000   15152.000000
75%    406431.00000      10.000000       4.130000   16791.000000
max    541908.00000   80995.000000   38970.000000   18287.000000

In [7]:
df.dtypes

index            int64
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [8]:
print(df.isnull().sum())

index               0
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
print("Cancelled invoices:",
      df["InvoiceNo"].astype(str).str.startswith("C").sum())

Cancelled invoices: 9288

In [11]:
print("Negative Quantities : ",
      (df["Quantity"]<0).sum())

Negative Quantities :  10624

In [12]:
print("Zero/Negative prices : ",
      (df["UnitPrice"]<=0).sum())

Zero/Negative prices :  2517

In [13]:
df[df["CustomerID"].isna()].head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom

In [14]:
df[df["InvoiceNo"].astype(str).str.startswith("C")].head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

In [15]:
df[df["Quantity"]<0].head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

In [16]:
df[df["UnitPrice"]<=0].head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom

In [17]:
print("Start Date: ",df["InvoiceDate"].min())
print("End Date : ",df["InvoiceDate"].max())

Start Date:  1/10/2011 10:04
End Date :  9/9/2011 9:52

In [18]:
print(df["CustomerID"].nunique())

4372

In [19]:
print(df["InvoiceNo"].nunique())

25900

In [20]:
clean_df =df.copy()
# remove cancelled invoices
clean_df= clean_df[~clean_df["InvoiceNo"].astype(str).str.startswith("C")]
#remove customerId that is null
clean_df=clean_df[clean_df["CustomerID"].notna()]
# keep positive quantities
clean_df=clean_df[clean_df["Quantity"]>0]
# keep postive price 
clean_df=clean_df[clean_df["UnitPrice"]>0]
# make a new column revenue 
clean_df["Revenue"]=clean_df["Quantity"] * clean_df["UnitPrice"]
#reset index
clean_df=clean_df.reset_index(drop=True)

print("OriginalRows: ",len(df))
print("CleanRows: ",len(clean_df))
print("Rows Removed : ",len(df)-len(clean_df))

OriginalRows:  541909
CleanRows:  397884
Rows Removed :  144025

In [21]:
#Check Cleaned Data 

print("Missing Customer Ids : ",clean_df["CustomerID"].isna().sum())
print("Negative Quantities :",(clean_df["Quantity"]<0).sum())
print("Negative or zero price :",(clean_df["UnitPrice"]<=0).sum())
print("Total Revenue : ",(clean_df["Revenue"]).sum())
print("Cancelled Invoices : ",(clean_df["InvoiceNo"].astype(str).str.startswith("C")).sum())
print("Unique Customers : ",clean_df["CustomerID"].nunique())
print("Unique Invoices : ",clean_df["InvoiceNo"].nunique())

Missing Customer Ids :  0
Negative Quantities : 0
Negative or zero price : 0
Total Revenue :  8911407.904
Cancelled Invoices :  0
Unique Customers :  4338
Unique Invoices :  18532

In [22]:
print("Start Date: ",clean_df["InvoiceDate"].min())
print("End Date : ",clean_df["InvoiceDate"].max())

Start Date:  1/10/2011 10:32
End Date :  9/9/2011 9:52

In [23]:
clean_df.shape

(397884, 10)

In [24]:
clean_df.to_csv("Online_retail_cleaned.csv",index=False)

In [28]:
customer_summary = (
    clean_df.groupby("CustomerID")
                    .agg(
        total_revenue=("Revenue","sum"),
        total_quantity=("Quantity","sum"),
        total_transactions=("InvoiceNo","count"),
        unique_invoices=("InvoiceNo","nunique"),
        first_purchase=("InvoiceDate","min"),
        last_purchase=("InvoiceDate","max")
).reset_index() 
                   )

customer_summary.head()

,CustomerID,total_revenue,total_quantity,total_transactions,unique_invoices,first_purchase,last_purchase
0,12346.0,77183.60,74215,1,1,1/18/2011 10:01,1/18/2011 10:01
1,12347.0,4310.00,2458,182,7,1/26/2011 14:30,8/2/2011 8:48
2,12348.0,1797.24,2341,31,4,1/25/2011 10:42,9/25/2011 13:13
3,12349.0,1757.55,631,73,1,11/21/2011 9:51,11/21/2011 9:51
4,12350.0,334.40,197,17,1,2/2/2011 16:01,2/2/2011 16:01

In [30]:
customer_summary.shape

(4338, 7)

In [31]:
customer_summary.describe()

,CustomerID,total_revenue,total_quantity,total_transactions,unique_invoices
count,4338.000000,4338.000000,4338.000000,4338.000000,4338.000000
mean,15300.408022,2054.266460,1191.289073,91.720609,4.272015
std,1721.808492,8989.230441,5046.081546,228.785094,7.697998
min,12346.000000,3.750000,1.000000,1.000000,1.000000
25%,13813.250000,307.415000,160.000000,17.000000,1.000000
50%,15299.500000,674.485000,379.000000,41.000000,2.000000
75%,16778.750000,1661.740000,992.750000,100.000000,5.000000
max,18287.000000,280206.020000,196915.000000,7847.000000,209.000000

In [36]:
#Top 10 Customers
top_customers=(customer_summary.sort_values("total_revenue",ascending=False).head(10))
print(top_customers)

      CustomerID  total_revenue  total_quantity  total_transactions  \
1689     14646.0      280206.02          196915                2076
4201     18102.0      259657.30           64124                 431
3728     17450.0      194550.79           69993                 337
3008     16446.0      168472.50           80997                   3
1879     14911.0      143825.06           80265                5675
55       12415.0      124914.53           77374                 714
1333     14156.0      117379.63           57885                1400
3771     17511.0       91062.38           64549                 963
2702     16029.0       81024.84           40208                 242
0        12346.0       77183.60           74215                   1

      unique_invoices    first_purchase    last_purchase
1689               73   1/14/2011 12:24   9/8/2011 11:28
4201               60  10/21/2011 11:54  9/28/2011 16:17
3728               46    1/11/2011 8:43   9/5/2011 13:52
3008                2    12/9/2011 9:15   5/18/2011 9:52
1879              201   1/18/2011 10:22   9/7/2011 14:13
55                 21    1/10/2011 9:58   9/1/2011 13:51
1333               55   1/14/2011 14:11   9/7/2011 16:00
3771               31    1/5/2011 12:40   9/7/2011 11:41
2702               63   1/13/2011 14:34    9/7/2011 9:45
0                   1   1/18/2011 10:01  1/18/2011 10:01

In [39]:
print(customer_summary["total_revenue"].mean())

2054.2664601198708

In [40]:
print(customer_summary["total_revenue"].median())

674.485

In [43]:
customer_summary["customer_type"]=np.where(customer_summary["unique_invoices"]==1,"one_time_customer","repeat_customer")
print(customer_summary.head())

   CustomerID  total_revenue  total_quantity  total_transactions  \
0     12346.0       77183.60           74215                   1
1     12347.0        4310.00            2458                 182
2     12348.0        1797.24            2341                  31
3     12349.0        1757.55             631                  73
4     12350.0         334.40             197                  17

   unique_invoices   first_purchase    last_purchase      customer_type
0                1  1/18/2011 10:01  1/18/2011 10:01  one_time_customer
1                7  1/26/2011 14:30    8/2/2011 8:48    repeat_customer
2                4  1/25/2011 10:42  9/25/2011 13:13    repeat_customer
3                1  11/21/2011 9:51  11/21/2011 9:51  one_time_customer
4                1   2/2/2011 16:01   2/2/2011 16:01  one_time_customer

In [45]:
print(customer_summary["customer_type"].value_counts())

customer_type
repeat_customer      2845
one_time_customer    1493
Name: count, dtype: int64

In [48]:
# What percentage of customers purchased only once?
print(customer_summary["customer_type"].value_counts(normalize=True)*100)

customer_type
repeat_customer      65.583218
one_time_customer    34.416782
Name: proportion, dtype: float64

In [54]:
repeat_customer_rate=((customer_summary["unique_invoices"]>1).sum() / len(customer_summary))*100

print(f"Repeat Customer Rate: {repeat_customer_rate :.2f}%")

Repeat Customer Rate: 65.58%

In [56]:
customer_summary["total_revenue"].describe()

count      4338.000000
mean       2054.266460
std        8989.230441
min           3.750000
25%         307.415000
50%         674.485000
75%        1661.740000
max      280206.020000
Name: total_revenue, dtype: float64